### ISSUE TITLE
자격증 항목 보충역 관련

### ISSUE THREAD

**Issue by wooogi123** [sesang06/awesome-alternative-military-service#16]
> https://work.mma.go.kr/caisBYIS/faq/BYITFAQSS.do;jsessionid=vMxuaHbMJAbgTHl5Ql0jmsmhqDpuuMIza3JAsbfhd8j7D0VckuMZ!722922163?menu_id=&pageIndex=2&pageUnit=10&searchCondition=&searchKeyword=&ilryeon_no=2000006569&faqctgry_cd=I03

해당 링크에 따르면 보충역의 경우 관련학과 전공, 기술훈련과정의 수료 또는 해당 분야의 복무경력을 갖춘 사람이라고 되어있는데, 본문에서는 보충역으로 대학 2학기 이상을 이수하였으면 '정보처리 기능사' 자격증이 필요하다고 되어있습니다.
해당 항목에 대한 수정이 필요합니다.

**Comment by sesang06** [comment]
* 단, 보충역은 정보처리기능사/산업기사/기사, 전자계산기조직응용기사 자격증 보유자인 경우 관련학과 전공, 기술훈련과정, 재직경력 1년이상인 경우 편입 가능

을 해석하시면,
2학기만 이수하셔도 정보처리기능사 자격증이 있으면 편입요건에 해당하는 것을 아실 수 있습니다.
(혹시 불안하시면 병무청에 편입 요건을 문의하셔도 됩니다.)

기타 요건을 추가하여 커밋했습니다. 감사합니다.
