### ISSUE TITLE
정보처리 IT 전문연구/산업기능요원 채팅방 비밀번호

### ISSUE THREAD

**Issue by JSpiner** [sesang06/awesome-alternative-military-service#8]
> 정보처리 IT 전문연구/산업기능요원 https://open.kakao.com/o/gE5Hf6G

본문에 나와있는 채팅방 링크에 비밀번호가 걸려있어 접근이 불가능합니다.
특정 집단을 위한 비공개 채팅방이라면 삭제하는게 맞고, 단순히 누락된거라면 비밀번호 추가가 필요합니다.

**Comment by mingkyme** [comment]
오픈채팅방 이름이
"정보처리 IT 전문연구/산업기능요원 비번:1024"
입니다.
1024 접근 가능하네요

**Comment by sesang06** [comment]
스팸 광고 유입 차단때문에 비밀번호를 걸어둔 것으로 알고 있습니다.
비밀번호를 추가해두도록 하겠습니다.

**Comment by LouiMinister** [comment]
혹시 비밀번호 바뀌었나요?

**Comment by Kim-Hojoon** [comment]
1024로는 그룹 채팅 참여가 되지 않는데, 바뀐 비밀번호 알려주실 수 있으신가요?
